### ISSUE TITLE
Replace GSAP with F1 for page transitions

### ISSUE THREAD

**Issue by njam3** [Jam3/generator-jam3#168]

**Comment by Jephuff** [comment]
should this be an option instead of straight replacing? For newsfeed we used gsap because the animation wasn't appropriate for f1(at least at the time)

**Comment by mikkoh** [comment]
What is the currently page transition that gets dropped in?

**Comment by njam3** [comment]
@mikkoh Its just an alpha tween. @Jephuff I would say change to f1 using the states.js / transitions.js file as we should be using f1 on our projects and it should be a rare case when we are not (in that case, the user can just remove it)

**Comment by Jephuff** [comment]
makes sense :+1:
