### ISSUE TITLE
Be able to transform index.html

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#170]
## Use case 1

Cache-busting

Even if #174 isn't implemented, you'd sometimes want to cache bust by changing the src of the files being included. Ideally this will be done automatically as part of the `release` task to eliminate the possibility of human error

```html
<!-- via filename -->
<script src="bundle-d41d8cd98f.js"></script>
```

```html
<!-- via querystring -->
<script src="bundle.js?d41d8cd98f"></script>
```

## Use case 2: 

When a project uses history.pushState (and pretty much every project should) but the client requires the project be served out of a subdirectory instead of at the root of a domain (BST, Success Academy). 

Typically script and css tags for pushState projects uses a root path slash, i.e.

```html
<script src="/js/app.js">
```

But for Success Academy, we have to serve the files out of 

```html
<script src="/middleschool/js/app.js">
```

and in the case if BST we had one single domain and had to rely on folders to separate our production, qa, and dev builds and needed different paths based on the environment

```html
<!-- production -->
<script src="/gamebench/js/app.js">
```

```html
<!-- dev -->
<script src="/dev/gamebench/js/app.js">
```

```html
<!-- qa -->
<script src="/qa/gamebench/js/app.js">
```

We have a [config file](https://github.com/Jam3/BST-Dashboard/blob/master/settings.js) that contains different values for different environments, the build task would read the config and transform index.html to use the right path depending on that environment variable

The reason `<base>` tags were not used was because it causes problems:  
http://stackoverflow.com/questions/1889076/is-it-recommended-to-use-the-base-html-tag  
https://www.drupal.org/node/13148  

And specific to BST, a lot of SVGs refer to filters and stuff by using ids via `#filterId`, base tags mess with that. Base tags also make relative links weird to deal with

## Use case 3: 

Integration with Wordpress (or other dynamic backend page) where a global variable is set on the php file via something like `window.config = <?php echo $config; ?>;`, during local development for the frontend team, it'd be useful to be able to develop without having to run a wordpress server, but we still want to work off of the same file to avoid duplication and having to replicate changes across files.

Example: 
The index.php:
https://github.com/Jam3/prj-fb-branding/blob/ab93d525ebc496f83fabf9a55a01ddf8522543cd/index.php#L46

The task that generates an index.html (which is _not_ checked into git), and replaces the `<?php echo $config; ?>` with a JSON string, and strips out all other php tags. The resulting index.html is then served for front-end local development
https://github.com/Jam3/prj-fb-branding/blob/ab93d525ebc496f83fabf9a55a01ddf8522543cd/gulpfile.babel.js#L70-L73

**Comment by njam3** [comment]
We will be implementing this in #174 and that will give a base for any transforming that could be done on a per project basis.
