### ISSUE TITLE
Cache-bust by revisioning assets to append content hashes to filenames

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#174]
e.g.: https://github.com/sindresorhus/gulp-rev

> unicorn.css → unicorn-d41d8cd98f.css

Sample usage: 
https://github.com/leonidas/gulp-project-template/blob/master/gulpfile.babel.js

FWIT, 

Steve Souders (author of the O'Reilly book "High Performance Websites") recommends against using query string
http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

And Google says using the filename is the typical way to go

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#invalidating-and-updating-cached-responses

More literature
http://webassets.readthedocs.org/en/latest/expiring.html#expire-using-the-filename

https://github.com/h5bp/server-configs-apache/blob/02a601e5914a504e019c46b76bb21adab89cb686/src/.htaccess#L677-692

I wouldn't say it's a "must have" if it's difficult to manually implement, but would certainly be nice

**Comment by iranreyes** [comment]
two main ways to unique things: timespan and hash.
for js and assets, in the case of assets rename only the folder
