### ISSUE TITLE
Split js bundles so that 3rd party libraries are in a separate `vendor.js`

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#175]
At some point during most projects you'll run across a bug where sourcemapping fails and you have to debug using line numbers referencing the gigantic bundle.js that takes 15 seconds to load every time something changes

We should be able to make that less painful by splitting up 3rd party files that is in the `package.json` so most of the time the only code we'd have to dig through are the more error-prone ones written by us

**Comment by njam3** [comment]
I like this, would reduce bundle time as well.

**Comment by njam3** [comment]
We will implement this once we figure out how to cross-require from bundles, i don't like the idea of polluting window and potentially having issues with other files.

**Comment by cheapsteak** [comment]
I've done this with BST using browserify's `external` API, no global variables :)

**Comment by cheapsteak** [comment]
Essentially have two browserify bundles

One bundles the app, which doesn't need to know that code splitting is happening at all, dependencies are still imported via `require`/`import`. When bundling that bundle, use browserify's `external` api to exclude an array of dependency names from the bundle (Read package.json and grab all the keys in `dependencies` and `peerDependencies`)

The other bundles the vendor file, which needs to be a separate entry point that can just be a blank file (I couldn't figure out how to do it with no blank file, it's like a catalyst to kick things off), then use browserify's `require` api to include those dependencies into this bundle

No change in workflow to the end-developer (except for perhaps an extra blank vendor.js ), no global variables :)

**Comment by cheapsteak** [comment]
Can I put a bounty on this? Having to debug a giant bundle.js is really slowing me down

**Comment by jmckinnell** [comment]
Huh? Isn't that what source maps are for?

**Comment by jmckinnell** [comment]
Or are you talking about load time?

**Comment by cheapsteak** [comment]
Two issues

- source maps are not produced for production builds, some errors only occur on the production server
- source maps don't always work, sometimes you have to dig into the raw code to see what your esnext code got transpiled to

**Comment by jmckinnell** [comment]
If the project isn't live yet, just turn on source maps temporarily while you de-bug to code, or even if it is and the bug is pressing enough turn it on anyway to fix it. Or build your production build to a release folder and test it from there by running an http-server.

**Comment by cheapsteak** [comment]
I appreciate the advice, but I must reiterate that source maps do solve all the problems that would cause you to crack open bundle.js to see what the browser is actually running

I was in the second situation earlier where source maps would not have helped. It was not the first nor I suspect the last time. 

Existing solutions exist for both browserify and webpack. I cannot see a downside to implementing this
