### ISSUE TITLE
Have as an option to merge `app` and `lib` to `src` [suggestion] 

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#176]
What is "app" and what is "lib", and why are they named the names they're named? 
If it's coming from pre-browserify node conventions then maybe we should re-aim for the folder structure of front-end apps that require a compilation step

Assuming #170 (Be able to transform index.html) happens, would that make it even murkier what the distinction between `app` and `lib` are?

`app` should perhaps be renamed `static`, or merged with `lib` to be `src`

A few references
1: https://github.com/kriasoft/react-starter-kit
^ 6k stars on github, uses `src` for source files

2: https://github.com/davezuko/react-redux-starter-kit
^ 2k stars on github, has `src/` and `src/static/` folder

3: https://github.com/AngularClass/angular2-webpack-starter
^ 1.9k stars on github, `src/` and `src/assets/`

**Comment by Jephuff** [comment]
broken into a couple of issues #183 and #184. app will be renamed to static and static files copied to .tmp to allow transforming.
