### ISSUE TITLE
Use .babelrc [suggestion]

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#178]
https://babeljs.io/docs/usage/babelrc/

A Missing .babelrc is [treated as problem](https://babeljs.io/blog/2015/11/03/babel-doctor) by babel-doctor

You'd also want to exclude and include certain transforms based on exeuction environment it could get  a bit lengthy, it'd be nice to extract that out from package.json and put it in its own thing

Would also have the added advantage of making it not limited to browserify, as webpack and also the commandline babel all know to respect `.babelrc`

**Comment by njam3** [comment]
This is fine by me, remove from package.json and make a .babelrc file.
