### ISSUE TITLE
Use browsersync for live-reloading

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#180]
Not sure if this should be an issue for Budo or here
Here's the issue:

Sometimes you have to do some crazy stuff like specify routes for a folder that actually points to your main directory, so `/middleschool/` is actually the root of your app, not `/`

It's easy to do with browser sync, but since we're using budo I'm not sure how to do this:

```js
  return browserSync({
    open: false,
    port: 9001,
    notify: false,
    ghostMode: false,
    server: {
      baseDir: paths.destination,
      routes: {
        [CONFIG.basePath]: "build" // <-- route all `/middleschool/` requests to the `build` directory
      },
      middleware: [
        modRewrite([
          '^[^\\.]*$ /index.html [L]' // <-- rewrite 404s to be handled by index.html (so if you're using pushstate, refreshing doesn't give you a page  not found error
        ])
      ]
    }
  });
```

Browser sync also has a much higher adoption rate than livereload

http://npmcharts.com/compare/livereload,browser-sync

**Comment by mattdesl** [comment]
I think you just want the `--pushstate` option.

**Comment by cheapsteak** [comment]
@mattdesl pushstate would solve modRewrite, but I don't think it solves the issue that browsersync's `routes` field does (allowing specifying key/vals for "url routes" and "local directories")

would you consider merging a PR that resolves https://github.com/mattdesl/budo/issues/140 ?

**Comment by njam3** [comment]
Would just prepending /middleschool/ to your routes not solve this problem? (and remove them for release). Sorry if I'm not understanding this one fully, I haven't had to do this before.

**Comment by mattdesl** [comment]
BrowserSync `routes` just adds a new static middleware:
https://github.com/BrowserSync/browser-sync/blob/1d86f1a8bae3d9228f732d3022644c2ebe521186/lib/server/utils.js#L61-L67

Is that what you want?

**Comment by cheapsteak** [comment]
Ah yes, looks like it would :)
Would it not be easier to use browsersync though instead of reimplementing features as they're needed? Api-compatibility would be nice too

**Comment by mattdesl** [comment]
It would pretty much lead to an entire rewrite of budo.

See here:
https://github.com/mattdesl/budo/issues/140#issuecomment-193349470

**Comment by mikkoh** [comment]
I wonder if you're having to do things like _"/middleschool/ is actually the root of your app, not /"_ that the app itself has strayed significantly from a standard generator/Jam3 project.

Hmmm... I'd say keep an eye on this and see if it happens often on "standard" projects and then decide on an action to take then.

**Comment by cheapsteak** [comment]
Closing this since Matt fixed my main pain point here
https://github.com/mattdesl/budo/issues/140#issuecomment-193360011
(thanks Matt!)
