### ISSUE TITLE
Change the favicon to a neutral image

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#181]
Serving the Jam3 favicon on a client's production site doesn't look good

**Comment by njam3** [comment]
Having the default favicon is great for internal sites and should remind you to update it on production sites. Creating a favicon is also part of the design checklist so it should always be created for a project.

**Comment by cheapsteak** [comment]
I'm not saying "no favicon" though, just not have it be the jam3 favicon to avoid the issue @jmckinnell @Jephuff had with newsfeed. I'm assuming the generator will be more frequently used for external projects than internal sites

**Comment by njam3** [comment]
But we want the jam3 favicon for all internal site, it also allows for easy updating since the code is already there, just have to replace files.
