### ISSUE TITLE
Add eslint file

### ISSUE THREAD

**Issue by njam3** [Jam3/generator-jam3#182]

**Comment by iranreyes** [comment]
Decide the default rules, we can begin with the old jslint rules and take care about rules in ES5, ES2016 and react(with JSX)

**Comment by cheapsteak** [comment]
I'd recommend starting with airbnb rules for both plain js and jsx

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**Comment by iranreyes** [comment]
I like it too

**Comment by njam3** [comment]
Yeah, our style guide (https://github.com/Jam3/Javascript-Code-Conventions) is based off airbnb with some slight modifications, so its a good place to start

**Comment by cheapsteak** [comment]
Some additional hoops to jump through for integrating with React and Babel:

https://github.com/yannickcr/eslint-plugin-react  
https://github.com/babel/babel-eslint  

Also need to make sure Sublime is parsing the file using `Javascript (Babel)` as the syntax and not `JSX`

![image](https://cloud.githubusercontent.com/assets/743976/14546154/8148b6a6-0271-11e6-9f53-a089a018dba0.png)

**Comment by iranreyes** [comment]
Add in the documentation more data like which IDE plugin should be used

**Comment by mattdesl** [comment]
On Gout we used this which seemed to work really well for our team:
https://github.com/Jam3/prj-gout/blob/master/.eslintrc

It required some additional devDependencies. We also had a [auto-formatter](https://github.com/Jam3/prj-gout/blob/b2dbfe26b759a4d1743030897c52aba8b56511e5/package.json#L33) which was useful when pulling in code from another project.

We also needed this ignore:
https://github.com/Jam3/prj-gout/blob/master/.eslintignore

Maybe @jmckinnell and @namniak can chip in.

**Comment by iranreyes** [comment]
I will take it a look @mattdesl and merge the rules with the current one. Thanks
