### ISSUE TITLE
Generate restrictive robots.txt unless ENV is production

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#191]
robots.txt should disallow everything unless process.env.NODE_ENV == production

**Comment by njam3** [comment]
While i like this idea, builds on jam3.net are considered production, at least with the current build process, and we definitely want the robots.txt there. We should investigate another way to ensure the robots.txt is everywhere except the live server.

**Comment by cheapsteak** [comment]
That's a good point
Perhaps a separate environment variable? Or check the host name of the machine to see if it's jam3.net? Is that possible?

**Comment by njam3** [comment]
After some research, best solution i have seen is having a robots.php mapped to robots.txt that dynamically writes it. This would work fine for jam3.net, but I'm not sure if its the best solution.

**Comment by njam3** [comment]
No viable in our current build process.
