### ISSUE TITLE
Be able to specify different files be used for different environments

### ISSUE THREAD

**Issue by cheapsteak** [Jam3/generator-jam3#200]
This is my gulp task using gulp-rename to allow different files be used for production
```diff
gulp.task('assets', () => {
  var pipeline = gulp.src(paths.assets.source);
+  if(production) {
+    pipeline = pipeline.pipe(rename(function (path) {
+      if (path.extname === '.production') {
+        path.extname = '';
+      }
+    }));
+  }
  return pipeline.pipe(gulp.dest(paths.assets.destination));
});
```

e.g. when you have:  
```bash
  src/assets/
    .htaccess
    .htaccess.production
```

When `production` is true, the file with the extension `.production` will be renamed and overwrite the original `.htaccess` when copied over to the build folder

Any files can have a production version

**Comment by njam3** [comment]
I believe this could be accomplished with via #199 if we provide a robust templating system. Something like handlebars would be fine in my mind.

**Comment by Jephuff** [comment]
closing, #199 will track updates for this.
