### ISSUE TITLE
Improve Generated Documentation + Generator documentation

### ISSUE THREAD

**Issue by mikkoh** [Jam3/generator-jam3#208]
It would be good to work on the generated documentation. Currently as a dev running the generator for the first time I need to make a lot of assumptions about how the generated application works without documentation.

In my mind here are the things I'd look at as a developer running the generator for the first time.
1. How do I run the application (`npm start`?)
2. Where do files live that I might need to modify
3. Where do I need to add code to add in a new pages/sections
4. Where should I put UI code?
5. What should the code look like that I add in/create. (do I need a preloader like App currently has for the react router)

Also it would be good to write a note in:
https://github.com/Jam3/generator-jam3/blob/master/README.md
That documentation for platform specific code will exist in the generated `README.md`.

Also might not be bad to explain what `vendor.js` is. I have no context for what it is but I'm asked to answer if I need a `vendor.js`

**Comment by iranreyes** [comment]
@mikkoh The advantage to use `vendor.js` is mainly for catching. The vendors on production has low probability to change, so it is a good idea split the code thinking on this

**Comment by cheapsteak** [comment]
For me it's also to have a smaller app.js, so that when I need to inspect the transpiled code (happens a few times each project) it doesn't take 45 seconds to open up each time the file changes

Perhaps a better prompt may be "would you like to extract third party dependencies into a separate vendor.js"

**Comment by njam3** [comment]
Add documentation on how to have more environments  in config.json
