### ISSUE TITLE
Add component "Not allow landscape rotation" for mobile

### ISSUE THREAD

**Issue by iranreyes** [Jam3/generator-jam3#233]
I have written this component three times, I think is a waste of time rewrite it all the time and is included in a lot of project on Jam3

**Comment by namniak** [comment]
@njam3 [PR](https://github.com/Jam3/generator-jam3/pull/245)
also added stringify + react inline svg

**Comment by jeremenichelli** [comment]
Couldn't this be an option when the project is generated?

**Comment by iranreyes** [comment]
I think is faster remove it than ask it at the beginning, mainly to avoid the overflow of questions. We should keep the questions for important structural or architectural changes.

**Comment by namniak** [comment]
Agreed. Questions are annoying. I'd rather remove a line of code. Personally.
