### ISSUE TITLE
Replace Redux devtools

### ISSUE THREAD

**Issue by namniak** [Jam3/generator-jam3#241]
Replace with https://github.com/zalmoxisus/redux-devtools-extension to boost performance.
The existing ones are adding lots of stuff to the DOM and with frequent store updates it drastically slows down the application.

**Comment by namniak** [comment]
@njam3 @iranreyes what do you guys think?

**Comment by iranreyes** [comment]
Seems a good idea, have you already used? @namniak

**Comment by namniak** [comment]
Yeah it's been used on at least 2-3 projects.
