### ISSUE TITLE
Use matchMedia for orientation detect

### ISSUE THREAD

**Issue by jeremenichelli** [Jam3/generator-jam3#273]
We should be using `matchMedia` instead of manually calculating the orientation of the screen. Checks on window's width and height can trigger layout unnecessarily (https://github.com/Jam3/generator-jam3/blob/master/templates/react/src/util/detect/index.js#L83).

matchMedia on MDN: https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

**Comment by njam3** [comment]
I agree that window width / height is not the best solution (especially since it caused problems for Android browsers when the keyboard is opened). I'll have to run some tests on matchMedia to see if it its a better solution to the issue.

**Comment by jeremenichelli** [comment]
I tested it and it works great. The only caveat is no IE9 support.

**Comment by neolwc** [comment]
@jeremenichelli might be related: #279

**Comment by njam3** [comment]
Looks like matchMedia may just be using browser width / height under the hood. It runs into the same issues with the Android Keyboard. I'll close this and evaluate PR #279.
