### ISSUE TITLE
Use classList instead of manupulating className property

### ISSUE THREAD

**Issue by jeremenichelli** [Jam3/generator-jam3#274]
We are currently doing string and array operations to add classes coming from the `detect` util results. We should be using `classList` since it has better performance and it is inside the browser spectrum we develop for.

**Comment by njam3** [comment]
classList is good, but I am hesitant to alter the current code as it is only run once (at the beginning of the app) so any performance gains would go unnoticed and it would remove support for IE9 (Although I hope we never have to support it again). Maybe if we use a polyfill for classList as well.

**Comment by jeremenichelli** [comment]
God, I thought we weren't supporting IE9 anymore. There is a polyfill that works well but adding a polyfill when we would be using this only when app kicks off makes no sense to me.

**Comment by njam3** [comment]
I'm pretty sure we don't have to support IE9 anymore, but I'm hesitant to make an update that reduces browser support for something this small. And I do agree with the polyfill comment, definitely would be overkill.
