### ISSUE TITLE
Research React Optimize Plugin

### ISSUE THREAD

**Issue by njam3** [Jam3/generator-jam3#278]
https://github.com/thejameskyle/babel-react-optimize

**Comment by jeremenichelli** [comment]
YES FINALLY 🎉

**Comment by mattdesl** [comment]
FWIW we are using this on Gout for production:
https://github.com/Jam3/prj-gout/blob/b2dbfe26b759a4d1743030897c52aba8b56511e5/scripts/bundleOptions.js#L13

The site doesn't feel any different but we haven't done any real benchmarks with this change, so it's hard to know.

**Comment by iranreyes** [comment]
Thanks @mattdesl, yeah our intention is to added in the generator.

**Comment by namniak** [comment]
Tested that on Success Academy as well. No issues. 
Though, can't say much about improvement as the project wasn't heavy

**Comment by namniak** [comment]
https://github.com/Jam3/generator-jam3/pull/320
