### ISSUE TITLE
Funny fact - Windows phone is detected as Android

### ISSUE THREAD

**Issue by iranreyes** [Jam3/generator-jam3#284]
The first is the UA and the second is what detect is throwing

![image](https://cloud.githubusercontent.com/assets/5953115/25284913/e812cba0-268e-11e7-902e-d5679eb3c151.png)

**Comment by namniak** [comment]
this should be fixed with https://github.com/Jam3/generator-jam3/pull/327. never tested on actual windows phone though

**Comment by namniak** [comment]
done
