### ISSUE TITLE
User needs to wait even when the site is ready

### ISSUE THREAD

**Issue by jeremenichelli** [Jam3/generator-jam3#290]
Though it might not be the common case, I found that the user needs to wait **1.5 seconds** even if the site is ready. I think this has _anti-pattern_ written all over the place and I would encourage to completely remove it.

👉 https://github.com/Jam3/generator-jam3/blob/master/templates/react/src/components/Preloader/index.js#L60

**Comment by njam3** [comment]
@jeremenichelli There is definitely a reason for this. I had to use it on my last project as the preloader animation needed to finish before we could leave the section (design trumping user experience). I agree that its wrong, but its something we have to change in our designs before we can remove it completely. I'll change the default to 0 for now.

**Comment by jeremenichelli** [comment]
Putting the default to `0` works for me, at least for now.

**Comment by njam3** [comment]
Fixed as of nyg@1.13.3
