### ISSUE TITLE
Missing checkEdge function

### ISSUE THREAD

**Issue by iranreyes** [Jam3/generator-jam3#297]
In `https://github.com/Jam3/generator-jam3/blob/master/templates/unsupported/none/src/unsupported.js#L19` the checkEdge is missing.

It should be here: `https://github.com/Jam3/generator-jam3/blob/master/templates/base/src/util/detect/util-browser.js`

Something like:

```
/**
 * This function will return whether this UtilBrowser we're running on is Microsoft Edge.
 *
 * @method checkEdge
 * @return {Boolean} If this function returns true we're running on Microsoft Edge, false if not.
 */
module.exports.checkEdge = function() {
  return ua.indexOf('edge') >= 0;
};
```

**Comment by namniak** [comment]
https://github.com/Jam3/generator-jam3/pull/327

**Comment by namniak** [comment]
done
