### ISSUE TITLE
Detect is failing with the version of Twitter in-app browser

### ISSUE THREAD

**Issue by iranreyes** [Jam3/generator-jam3#298]
The function `utilBrowser.checkVersion() ` is throwing the whole user agent when the browser is the `twitter` in-app browser.

Possible solution:

```
  if (checkTwitter()) {
    // Apple, There is not version, taken from the OS
    if (ua.indexOf('twitter for iphone') >= 0) {
      var OSApp = ua.match(/OS \s*(\d+)/i);
      return OSApp[1];
    }

    //Android, Take the chrome version
    if (M[1] === 'chrome') {
      return M[2];
    }
  }
```

**Comment by pbellesa** [comment]
Do you want to add the instagram too? 
```
    var checkInstagram = function() {
      return (ua.indexOf("instagram") > -1) || (ua.indexOf("instagram") > -1);
    };
```

**Comment by iranreyes** [comment]
I will test it @pbellesa and I will include it in a more general solution. Thx

**Comment by iranreyes** [comment]
Random Ideas: 
1. This unsupported checking should be a module.
2. The detection checking should be inclusive, so everything we don't specify will be accepted. That let the door open for unknown things.

**Comment by jeremenichelli** [comment]
I agree with last Comment from Iran. I remember proposing this to @njam3 when we had the facebook in-app browser issue in Doritos. If suddenly a new and modern browsers comes in or some known browser changes the UA string we can get undesired consequences.

**Comment by njam3** [comment]
@iranreyes 

1. Yes, definitely.
2. This will be accomplished once we implement this: https://github.com/Jam3/generator-jam3/issues/286

**Comment by iranreyes** [comment]
@njam3 I already have an inclusive implementation, I will post it as a PR and we can improve it there. ;-)

https://github.com/Jam3/prj-oculus-branding/blob/master/src/util/unsupportedUtils.js#L9

**Comment by namniak** [comment]
https://github.com/Jam3/generator-jam3/pull/327

**Comment by namniak** [comment]
done
