### ISSUE TITLE
Create Common Hamburger Menu

### ISSUE THREAD

**Issue by njam3** [Jam3/generator-jam3#307]

**Comment by namniak** [comment]
is this a hamburger button with idle/active states or a slide in/out menu? The slide menu is not widely used. Button with onOpen & onClose hooks makes sense though

**Comment by njam3** [comment]
I would argue that both are viable. A button those goes from 3 lines to an X and a Slide Out menu. I would say the majority of our mobile sites have home form of a slide out menu.

**Comment by neo** [comment]
but different ways of animating in

**Comment by neo** [comment]
and for the button: https://github.com/jonsuh/hamburgers

**Comment by namniak** [comment]
here's the hamburger button PR https://github.com/Jam3/generator-jam3/pull/330

**Comment by namniak** [comment]
done
