### ISSUE TITLE
Migrating detect browser utility for an open source library

### ISSUE THREAD

**Issue by iranreyes** [Jam3/generator-jam3#311]
Currently our detect library is using inside `mobile-detect` and custom code to check browsers. Will be a good idea if we migrate the custom code for an open source library.

First options:
https://www.npmjs.com/package/useragent (The amount of downloads are crazy)
https://www.npmjs.com/package/bowser (I have used this one)

**Comment by namniak** [comment]
https://github.com/Jam3/generator-jam3/pull/327

**Comment by namniak** [comment]
done
