### ISSUE TITLE
According to React Developer Tool our sites are not running react in production mode

### ISSUE THREAD

**Issue by iranreyes** [Jam3/generator-jam3#332]
After installing React Developer Tool in Chrome you will notice that the icon change depending on if React is in dev mode or production mode (it also has more states that I won't cover here).

Our production sites are showing as in developer mode and not in production mode. I quickly checked and seems that we are setting correctly React for production but for some reason is not detected like this.

![image](https://user-images.githubusercontent.com/5953115/28033390-7d44a7fa-6584-11e7-8e29-d9618561b96b.png)

Note: This is public for everyone with the addon added to chrome

**Comment by neo** [comment]
@iranreyes do you know a quick way to fix this?
