### ISSUE TITLE
To use yarn

### ISSUE THREAD

**Issue by iranreyes** [Jam3/generator-jam3#344]
++ Speed
++ Consistency with package versions
++ Out of the box license viewer/fetcher
== Same npm packages
=~ Similar commands

**Comment by neo** [comment]
I thought most of the problems are solved by npm5

**Comment by njam3** [comment]
Yeah, I am on the same page as @neo. I thought the latest npm addressed all the benefits of yarn, is there still something that is missing that we can benefit from the switch?
