### ISSUE TITLE
Proposal: Remove stats.js

### ISSUE THREAD

**Issue by neo** [Jam3/generator-jam3#345]
Chrome devtools now come with a fps meter: https://developer.chrome.com/devtools/docs/rendering-settings

**Comment by cmndo** [comment]
Devtools doesn't look like that to me:

> Note: In Chrome 58 the Timeline panel was renamed to the Performance panel.
[Devtools Documentation](https://developers.google.com/web/tools/chrome-devtools/#performance)

I don't see an FPS counter in Devtools Version 61.0.3163.100 (Official Build) (64-bit)

1. Press Command+Shift+P (Mac) or Control+Shift+P (Windows, Linux) to open the Command Menu.
2. Start typing Rendering in the Command Menu and select Show Rendering.
3. In the Rendering tab, enable FPS Meter. A new overlay appears in the top-right of your viewport.

Nice.

**Comment by njam3** [comment]
Going to leave Stats.js in for now since we still need a fps meter in all other browsers.
