### ISSUE TITLE
Installing from source

### ISSUE THREAD

**Issue by mikehwagz** [Jam3/generator-jam3#348]
Hey Jam3 👋 

This generator is awesome and I am eager to experiment with some of the new features on master such as the video player component and audio utility. How should I go about installing the generator from the source?

Thanks in advance 🍻

**Comment by neo** [comment]
Hi @mikehwagz! Thank you for your interest!

Would this help?

![image](https://user-images.githubusercontent.com/9028430/32502611-2f473fc6-c3a9-11e7-8069-cf96fbc0bbc0.png)

**Comment by mikehwagz** [comment]
Yes! Thank you so much for the quick response! 👍

**Comment by mikehwagz** [comment]
Will do 🙂
