### ISSUE TITLE
Standardized approach to sprites / texture packing

### ISSUE THREAD

**Issue by mattdesl** [Jam3/generator-jam3#41]
some ramblings / thoughts on texture packing
- I've enjoyed having raw sprites in Git, it means you can safely roll back to a commit or tag (i.e. "we know it was working 2 days ago") and the site/icons will work fine
- some projects are more sprite-sheet heavy though and it might not be good to have them commit huge raw assets to github
- we should approach retina, scaling, @2x, and such in a standard way. @maxtherocket did some of this on AdBlitz a while back and it worked well for that project
- I am finding on some WebGL projects that sprites should be split based on texture parameters. For example; we might have a bunch of UI icons that need `gl.NEAREST` for pixel scaling. Others end up needing `gl.LINEAR` for smooth scaling. This means we need two texture atlases. Maybe more if we aim to support mipmapping on a subset of textures (like bitmap font glyphs)

**Comment by njam3** [comment]
We no longer see sprites being used often on projects, closing this for now.
